---

- name: Ensure pip is installed
  ansible.builtin.apt:
    name: python3-pip

- name: Ensure certbot is installed
  ansible.builtin.pip:
    name: certbot

- name: Ensure certbot-dns-hetzner is installed
  ansible.builtin.pip:
    name: certbot-dns-hetzner
  when: certbot_dns_hetzner

- name: Ensure certbot-dns-scaleway is installed
  ansible.builtin.pip:
    name: certbot-dns-scaleway
  when: certbot_dns_scaleway

- name: Ensure certbot-dns-digitalocean is installed
  ansible.builtin.pip:
    name: certbot-dns-digitalocean
  when: certbot_dns_digitalocean

...
