---

- name: Ensure software-properties-common is installed
  ansible.builtin.apt:
    name: software-properties-common

- name: Ensure snap is installed
  ansible.builtin.apt:
    name: snapd

- name: Ensure certbot is installed
  community.genereal.snap:
    name: certbot
    
- name: Ensure pip is installed
  ansible.builtin.apt:
    name: python3-pip
  when: certbot_dns_hetzner

- name: Ensure certbot-dns-hetzner is installed
  ansible.builtin.pip:
    name: certbot-dns-hetzner
  when: certbot_dns_hetzner

...
